\c e_power_house

INSERT INTO ventas.producto (nombre, descripcion, precio_unidad, costo_unidad)
VALUES
    ('Televisor Samsung', 'Televisor de alta definición con pantalla de 55 pulgadas y resolución 4K', 899.99, 650.00),
    ('Refrigerador LG', 'Refrigerador de dos puertas con capacidad de 25 pies cúbicos y dispensador de agua y hielo', 1299.99, 900.00),
    ('Horno eléctrico Whirlpool', 'Horno eléctrico de 30 pulgadas con capacidad de 5.3 pies cúbicos y tecnología de autolimpieza', 799.99, 550.00),
    ('Lavadora Samsung', 'Lavadora de carga frontal con capacidad de 4.5 pies cúbicos y tecnología de lavado con burbujas', 899.99, 600.00),
    ('Secadora LG', 'Secadora eléctrica con capacidad de 7.3 pies cúbicos y tecnología de secado con sensor de humedad', 799.99, 550.00),
    ('Aspiradora Dyson', 'Aspiradora inalámbrica con motor digital V11 y sistema de filtración avanzado', 399.99, 300.00),
    ('Batidora KitchenAid', 'Batidora de pedestal con tazón de acero inoxidable de 5 cuartos de galón y diez velocidades', 349.99, 250.00),
    ('Licuadora Oster', 'Licuadora con motor de 1200 vatios y cuchillas de acero inoxidable', 99.99, 75.00),
    ('Cafetera Keurig', 'Cafetera de una sola taza con tecnología de preparación rápida y cinco opciones de tamaño de taza', 89.99, 65.00),
    ('Microondas Panasonic', 'Microondas de 1.2 pies cúbicos con tecnología de cocción por sensor y diez niveles de potencia', 129.99, 90.00),
    ('Aire acondicionado LG', 'Aire acondicionado de ventana con capacidad de 10,000 BTU y función de ahorro de energía', 299.99, 225.00),
    ('Ventilador de torre Honeywell', 'Ventilador de torre con tecnología de oscilación y control remoto', 79.99, 60.00),
    ('Calefactor Lasko', 'Calefactor portátil con termostato ajustable y tecnología de protección de seguridad', 49.99, 35.00),
    ('Robot de cocina Ninja', 'Robot de cocina multifuncional con ocho opciones de funciones y tecnología de autoampliación', 199.99, 150.00),
    ('Plancha Black+Decker', 'Plancha de vapor con tecnología de planchado vertical y selector de temperatura', 29.99, 20.00),
    ('Exprimidor Hamilton Beach', 'Exprimidor eléctrico con tecnología de extracción de jugo de alta velocidad y filtro de pulpa', 49.99, 35.00),
    ('Cuchillo eléctrico Black+Decker', 'Cuchillo eléctrico con cuchilla de acero inoxidable y sistema de bloqueo de seguridad', 39.99, 30.00),
    ('Máquina de hacer pan Oster', 'Máquina para hacer pan con 12 programas de cocción y capacidad de 2 libras', 149.99, 100.00),
    ('Freidora de aire Philips', 'Freidora de aire con capacidad de 2.75 cuartos de galón y tecnología de cocción rápida', 199.99, 140.00),
    ('Batidora de mano Cuisinart', 'Batidora de mano con motor de 220 vatios y accesorios para picar y batir', 79.99, 55.00),
    ('Hervidor eléctrico Hamilton Beach', 'Hervidor eléctrico con capacidad de 1.7 litros y tecnología de apagado automático', 39.99, 30.00),
    ('Máquina de espresso DeLonghi', 'Máquina de espresso con tecnología de preparación de doble pared y sistema de espuma', 599.99, 400.00),
    ('Cafetera DeLonghi', 'Cafetera de goteo programable con capacidad de 12 tazas y función de pausa y servido', 99.99, 70.00),
    ('Molinillo de café Krups', 'Molinillo de café eléctrico con capacidad para moler hasta 12 tazas de café', 49.99, 35.00),
    ('Procesador de alimentos KitchenAid', 'Procesador de alimentos con capacidad de 7 tazas y tres velocidades', 149.99, 100.00),
    ('Plancha de gofres Cuisinart', 'Plancha de gofres con capacidad para preparar cuatro gofres a la vez y termostato ajustable', 69.99, 50.00),
    ('Sartén eléctrico Hamilton Beach', 'Sartén eléctrico con capacidad de 12 pulgadas y tecnología de calentamiento rápido', 59.99, 45.00),
    ('Horno tostador Black+Decker', 'Horno tostador con capacidad de 6 rebanadas de pan y tecnología de convección', 69.99, 50.00),
    ('Tostadora Cuisinart', 'Tostadora de cuatro rebanadas con tecnología de control de temperatura y funciones de descongelación y recalentamiento', 49.99, 35.00),
    ('Licuadora de inmersión KitchenAid', 'Licuadora de inmersión con motor de 200 vatios y accesorios para batir y picar', 99.99, 70.00),
    ('Máquina de helados Cuisinart', 'Máquina para hacer helados con capacidad de 2 cuartos de galón y tecnología de congelación rápida', 219.99, 160.00),
    ('Máquina de palomitas de maíz West Bend', 'Máquina para hacer palomitas de maíz con capacidad de 4 onzas y tecnología de cocción rápida', 69.99, 50.00),
    ('Olla arrocera Aroma', 'Olla arrocera programable con capacidad de 8 tazas y tecnología de cocción a presión', 79.99, 55.00),
    ('Plancha eléctrica Hamilton Beach', 'Plancha eléctrica con superficie antiadherente y tecnología de calentamiento rápido', 39.99, 30.00),
    ('Barbacoa eléctrica George Foreman', 'Barbacoa eléctrica con superficie de cocción inclinada y tecnología de drenaje de grasa', 69.99, 50.00),
    ('Horno de pizza Oster', 'Horno de pizza con capacidad de 12 pulgadas y tecnología de cocción uniforme', 119.99, 80.00),
    ('Hervidor eléctrico Aicok', 'Hervidor eléctrico con capacidad de 1.7 litros y tecnología de apagado automático', 39.99, 30.00),
    ('Sartén eléctrico Black+Decker', 'Sartén eléctrico con capacidad de 12 pulgadas y tecnología de calentamiento rápido', 49.99, 35.00),
    ('Tostadora de sandwich Hamilton Beach', 'Tostadora de sandwich con capacidad para preparar dos sandwiches a la vez y tecnología de cocción uniforme', 29.99, 20.00),
    ('Máquina para hacer pan Hamilton Beach', 'Máquina para hacer pan con capacidad de hasta 2 libras de pan y 12 ciclos de horneado', 89.99, 65.00),
    ('Tostadora KitchenAid', 'Tostadora de dos rebanadas con tecnología de control de temperatura y funciones de descongelación y recalentamiento', 59.99, 40.00),
    ('Batidora de pedestal KitchenAid', 'Batidora de pedestal con tazón de acero inoxidable de 5 cuartos y 10 velocidades', 249.99, 190.00),
    ('Olla de cocción lenta Crock-Pot', 'Olla de cocción lenta con capacidad de 6 cuartos y tecnología de cocción programable', 59.99, 45.00),
    ('Freidora de aire Black+Decker', 'Freidora de aire con capacidad de 2.75 cuartos y tecnología de cocción sin aceite', 199.99, 150.00),
    ('Molinillo de especias Cuisinart', 'Molinillo de especias eléctrico con cuchillas de acero inoxidable y tapa para almacenamiento', 39.99, 25.00),
    ('Exprimidor de cítricos Breville', 'Exprimidor de cítricos con motor de 100 vatios y tecnología de extracción de jugo', 149.99, 110.00),
    ('Máquina de hacer pasta Philips', 'Máquina de hacer pasta con accesorios para preparar espagueti, fettuccini y lasaña', 299.99, 220.00),
    ('Hervidor de huevos Dash', 'Hervidor de huevos eléctrico con capacidad de 6 huevos y tecnología de apagado automático', 19.99, 15.00),
    ('Máquina para hacer waffles Oster', 'Máquina para hacer waffles con capacidad de 4 waffles a la vez y tecnología de cocción uniforme', 59.99, 45.00),
    ('Licuadora personal Ninja', 'Licuadora personal con motor de 700 vatios y tecnología de trituración de hielo', 49.99, 35.00),
    ('Batidora de mano Ham', 'Batidora de mano con motor de 200 vatios y accesorios para batir y picar', 49.99, 35.00),
    ('Hervidor de agua Bodum', 'Hervidor de agua eléctrico con capacidad de 1.5 litros y tecnología de apagado automático', 29.99, 20.00),
    ('Olla instantánea Instant Pot', 'Olla a presión programable con capacidad de 6 cuartos y 13 programas de cocción', 129.99, 95.00),
    ('Procesador de alimentos Cuisinart', 'Procesador de alimentos con capacidad de 11 tazas y tres velocidades', 169.99, 120.00),
    ('Máquina para hacer panini Hamilton Beach', 'Máquina para hacer panini con capacidad de dos sándwiches a la vez y tecnología de cocción uniforme', 49.99, 35.00),
    ('Sartén eléctrico Aroma', 'Sartén eléctrico con tapa de vidrio y temperatura ajustable para cocinar', 39.99, 25.00),
    ('Máquina para hacer helados Cuisinart', 'Máquina para hacer helados con capacidad de 1.5 cuartos y tecnología de enfriamiento automático', 249.99, 185.00),
    ('Máquina para hacer crepes NutriChef', 'Máquina para hacer crepes con placa antiadherente y temperatura ajustable', 49.99, 30.00),
    ('Horno tostador Black & Decker', 'Horno tostador con capacidad de 4 rebanadas de pan y tecnología de convección', 69.99, 50.00),
    ('Máquina para hacer palomitas de maíz Great Northern', 'Máquina para hacer palomitas de maíz con capacidad de hasta 12 tazas y tecnología de calentamiento uniforme', 69.99, 55.00),
    ('Máquina para hacer café Keurig', 'Máquina para hacer café con tecnología de preparación de una taza a la vez y depósito de agua de 48 onzas', 119.99, 85.00),
    ('Plancha eléctrica Oster', 'Plancha eléctrica con superficie antiadherente y temperatura ajustable', 39.99, 25.00),
    ('Exprimidor de jugos Black & Decker', 'Exprimidor de jugos con motor de 30 vatios y cono de doble tamaño para frutas grandes y pequeñas', 29.99, 20.00),
    ('Licuadora de inmersión Mueller Austria', 'Licuadora de inmersión con motor de 500 vatios y accesorios para batir y picar', 39.99, 30.00),
    ('Máquina para hacer hot dogs Nostalgia', 'Máquina para hacer hot dogs con capacidad de hasta 8 hot dogs y tecnología de cocción uniforme', 39.99, 30.00),
    ('Máquina para hacer algodón de azúcar VIVO', 'Máquina para hacer algodón de azúcar con capacidad de hasta 20 conos y tecnología de calentamiento rápido', 299.99, 220.00),
    ('Horno eléctrico Black & Decker', 'Horno eléctrico con capacidad de 6 rebanadas de pan y tecnología de convección', 89.99, 70.00),
    ('Batidora de mano KitchenAid', 'Batidora de mano con motor de 250 vatios y accesorios para batir y picar', 99.99, 75.00),
    ('Molinillo de café Copium', 'Molinillo de café eléctrico con cuchillas de acero inoxidable y ajuste de grosor de molienda', 49.99, 35.00),
    ('Máquina para hacer donas Babycakes', 'Máquina para hacer donas con capacidad de hasta 7 donas y tecnología de cocción uniforme', 39.99, 25.00),
    ('Licuadora Osterize', 'Licuadora con motor de 600 vatios y tecnología de trituración de hielo', 69.99, 50.00),
    ('Máquina para hacer sopa Blendtec', 'Máquina para hacer sopa con capacidad de 4 tazas y tecnología de cocción rápida', 199.99, 160.00),
    ('Máquina para hacer waffles Hamilton Beach', 'Máquina para hacer waffles con placa antiadherente y tecnología de cocción uniforme', 29.99, 20.00),
    ('Máquina para hacer pasta Marcato Atlas 150', 'Máquina para hacer pasta con accesorios para fettuccine, spaghetti y lasaña', 149.99, 120.00),
    ('Freidora de aire sin aceite GoWISE USA', 'Freidora de aire sin aceite con capacidad de 5.8 cuartos y tecnología de cocción uniforme', 99.99, 75.00),
    ('Máquina para hacer yogurt Euro Cuisine', 'Máquina para hacer yogurt con capacidad de 7 tarros y tecnología de cocción uniforme', 39.99, 30.00),
    ('Máquina para hacer crema batida ICO', 'Máquina para hacer crema batida con tecnología de doble acción y accesorios para decoración', 39.99, 25.00),
    ('Molinillo de especias Cuisine art', 'Molinillo de especias eléctrico con cuchillas de acero inoxidable y capacidad de 90 gramos', 39.99, 30.00),
    ('Máquina para hacer pan Cuisinart', 'Máquina para hacer pan con capacidad de 2 libras y tecnología de cocción uniforme', 99.99, 75.00),
    ('Máquina para hacer fideos ZENSTYLE', 'Máquina para hacer fideos con accesorios para fideos de diferentes formas y tecnología de cocción uniforme', 129.99, 95.00),
    ('Plancha eléctrica Hamilton City', 'Plancha eléctrica con superficie antiadherente y temperatura ajustable', 29.99, 20.00),
    ('Máquina para hacer palomitas de maíz West Bend', 'Máquina para hacer palomitas de maíz con tecnología de calentamiento rápido y bandeja para servir', 39.99, 25.00),
    ('Máquina para hacer algodón de azúcar Clevr', 'Máquina para hacer algodón de azúcar con capacidad de hasta 7 conos y tecnología de calentamiento uniforme', 129.99, 95.00),
    ('Molinillo de café Baratza Encore', 'Molinillo de café eléctrico con cuchillas cónicas y ajuste de grosor de molienda', 139.99, 110.00),
    ('Máquina para hacer helados Hamilton Beach', 'Máquina para hacer helados con capacidad de 1.5 cuartos y tecnología de enfriamiento automático', 69.99, 50.00),
    ('Máquina para hacer crepes Hamilton Beach', 'Máquina para hacer crepes con placa antiadherente y tecnología de cocción uniforme', 39.99, 25.00);
